apiVersion: v1
kind: Pod
metadata:
  name: alpine-2
  namespace: default
spec:
  containers:
    - image: alpine:3.2
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      imagePullPolicy: IfNotPresent
      name: alpine-2
  restartPolicy: Always